### ISSUE TITLE
NoClassDefFoundError sometimes.

### ISSUE THREAD

**Issue by pepyakin** [orfjackal/retrolambda#37]
I have strange issue for a quite some time, sometimes when I build my app, following exception occur.

```
    java.lang.NoClassDefFoundError: com.wheely.app.utils.PhoneCodeUtils$$Lambda$1
            at com.wheely.app.utils.PhoneCodeUtils.preloadPhoneNumberUtil(PhoneCodeUtils.java:133)
            at com.wheely.app.WheelyApplication.onCreate(WheelyApplication.java:92)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4328)
            at android.app.ActivityThread.access$1500(ActivityThread.java:135)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5001)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
            at dalvik.system.NativeStart.main(Native Method)
```

This is first occurrence of lambda on code path, so I think that either retrolambda didn't run or it's result classes not included in final dex. Cleaning the project usually makes the deal.
But it seems this happens more frequently eventually.
I tend to think it is somehow related to incremental building, but not sure.

**Comment by Diolor** [comment]
Any news on that topic? e.g. solved with a newer version of e.g gradle?

**Comment by dlew** [comment]
I've seen this issue repeatedly as well. What's interesting is that it only seems to affect certain classes; put a lambda *anywhere* in one, and it will eventually run into this issue, repeatedly, through multiple cleans. But most classes don't run into it.

I'll try running some debugging on it next time I run into this, to figure out what is different about these classes in particular.

**Comment by erickok** [comment]
I am experiencing this as well and can confirm that it is resolved when I perform a 'gradle clean' and rebuild. I will try to isolate a minimal reproducible example.

**Comment by evoxmusic** [comment]
Hi all,

I still get this error as well, by performing "gradle clean" and rebuild it seems to clear the problem but is there any fix coming ? 

Thanks

**Comment by alwaysthecritic** [comment]
I'm seeing this as well - exactly as described by others. Usually crops up in the same place in the same class. Anecdotally, I also have been noticing that sometimes the app doesn't reflect my code changes, which drives me crazy figuring out why things weren't working for a while, but then it magically starts working as it (presumably) finally picks up my new code. This has only happened in recent weeks and is the first time my dev experience has been anything other than rock solid.

**Comment by IlyaEremin** [comment]
I'm also face with the problem only on certain classes and I can't figure out on what depends this error. It appears random. I use RxJava and retrofit, but I think that most of retrolambda users use these libraries.

**Comment by teddis** [comment]
I had this problem today as well and can confirm that rebuilding/cleaning fixed the problem. I'm using AndroidStudio 1.1 Beta 4 with Gradle 1.0.0 and RxJava using gradle dependency compile 'io.reactivex:rxandroid:0.23.0'. I got the following exception when trying to open a new activity:

```
02-17 15:54:52.160 W/System.err(19910): java.lang.NoClassDefFoundError: com.gameontechnology.gameon.ui.activity.AcceptInviteActivity$$Lambda$1
02-17 15:54:52.160 W/System.err(19910): 	at com.gameontechnology.gameon.ui.activity.AcceptInviteActivity.onCreate(AcceptInviteActivity.java:56)
```
which references the following code in my onCreate method:

```java
        closeButton.setOnClickListener(v -> finish());
```

**Comment by rafaeltoledo** [comment]
Same problem here. Seems to be something related with Android Gradle plugin. I was using 1.1.0 and was facing the crash. After downgrading to 1.0.1, the crash went away. Maybe something new in the plugin is causing this?

I'm using the gradle plugin 2.5.0 with retrolambda 1.8.1

**Comment by osunnarvik** [comment]
Looks like I have a deterministic way of reproducing this issue, have been reproducing 10 times in a row now by the following scenario.

I have two classes (ClassA and ClassB). ClassB contains lambdas, and ClassA is the one that allocates ClassB. 
If I make a change in ClassA without making a change in ClassB, I get this issue. Whenever I make a change in ClassB, the problem goes away.

So, it naturally enough does not rebuild ClassB when there are no changes in ClassB, but why does it remove the lambda-class of ClassB when the one that allocates ClassB is changed?

**Comment by Diolor** [comment]
@osunnarvik Your replication is correct. The conflict might be with Dex/pre-Dexing.

For the time: you can use proguard to catch that in the compilation and see if you need a clean build

**Comment by daveztong** [comment]
@osunnarvik You are right. I did reproduce this issue by following the scenario you described.

 I'm facing the same problem as well. It only happens in one place. Clean and rebuild fix the problem. I'm also using RxJava and retrofit.

**Comment by evant** [comment]
Anyone running into this issue, can you try updating to 3.0.0 and setting incremental to false? If that fixes it then it's definitely and issue in the gradle plugin.

**Comment by evant** [comment]
Also, @osunnarvik or anyone else, mind posting a sample project that has the issue as you describe it. I tried to reproduce it with my own ClassA and ClassB myself, but couldn't. There might be something more subtle here that I'm missing.

**Comment by cre8ivejp** [comment]
I have the same problem here using the version 2.5.0
clean and build the project it seems to solve the problem.

**Comment by osayilgan** [comment]
Here it's, check out my logs. It's persistent in my case. After Clean and Rebuild it works in my Local environment but not in CI server.

```
Saving lambda class: com/myapp/android/view/document/website/PrintWebsiteFragment$1$$Lambda$1
Error! Failed to transform some classes
java.lang.RuntimeException: java.lang.IllegalAccessException: no such method: com.myapp.android.view.history.HistoryActivity.lambda$onBackPressed$39()void/invokeSpecial
	at net.orfjackal.retrolambda.lambdas.LambdaReifier.reifyLambdaClass(LambdaReifier.java:42)
	at net.orfjackal.retrolambda.lambdas.BackportLambdaInvocations$InvokeDynamicInsnConverter.backportLambda(BackportLambdaInvocations.java:105)
	at net.orfjackal.retrolambda.lambdas.BackportLambdaInvocations$InvokeDynamicInsnConverter.visitInvokeDynamicInsn(BackportLambdaInvocations.java:94)
	at net.orfjackal.retrolambda.asm.ClassReader.readCode(ClassReader.java:1439)
	at net.orfjackal.retrolambda.asm.ClassReader.readMethod(ClassReader.java:1017)
	at net.orfjackal.retrolambda.asm.ClassReader.accept(ClassReader.java:693)
	at net.orfjackal.retrolambda.asm.ClassReader.accept(ClassReader.java:506)
	at net.orfjackal.retrolambda.Transformers.transform(Transformers.java:99)
	at net.orfjackal.retrolambda.Transformers.backportClass(Transformers.java:44)
	at net.orfjackal.retrolambda.Retrolambda.run(Retrolambda.java:73)
	at net.orfjackal.retrolambda.Main.main(Main.java:26)
Caused by: java.lang.IllegalAccessException: no such method: com.myapp.android.view.history.HistoryActivity.lambda$onBackPressed$39()void/invokeSpecial
	at java.lang.invoke.MemberName.makeAccessException(MemberName.java:869)
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:990)
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1382)
	at java.lang.invoke.MethodHandles$Lookup.findSpecial(MethodHandles.java:1000)
	at net.orfjackal.retrolambda.lambdas.Types.toMethodHandle(Types.java:42)
	at net.orfjackal.retrolambda.lambdas.Types.asmToJdkType(Types.java:19)
	at net.orfjackal.retrolambda.lambdas.LambdaReifier.callBootstrapMethod(LambdaReifier.java:106)
	at net.orfjackal.retrolambda.lambdas.LambdaReifier.reifyLambdaClass(LambdaReifier.java:37)
	... 10 more
Caused by: java.lang.NoClassDefFoundError: android/support/v4/widget/DrawerLayoutImpl
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at net.orfjackal.retrolambda.NonDelegatingClassLoader.loadClass(NonDelegatingClassLoader.java:25)
	at java.lang.invoke.MethodHandleNatives.resolve(Native Method)
	at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:962)
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:987)
	... 16 more
Caused by: java.lang.ClassNotFoundException: android.support.v4.widget.DrawerLayoutImpl
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.orfjackal.retrolambda.NonDelegatingClassLoader.loadClass(NonDelegatingClassLoader.java:27)
	... 29 more
:app:compileRetrolambdaBfgDebug FAILED
:app:compileRetrolambdaBfgDebug (Thread[Daemon worker,5,main]) completed. Took 6.619 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileRetrolambdaBfgDebug'.
> Process 'command '/usr/lib/jvm/jdk1.8.0/bin/java'' finished with non-zero exit value 1

* Try:
Run with --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:compileRetrolambdaBfgDebug'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:305)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
	at org.gradle.execution.taskgraph.ParallelTaskPlanExecutor.process(ParallelTaskPlanExecutor.java:51)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:29)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
	at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:47)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:34)
	at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:35)
	at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:24)
	at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
	at org.gradle.launcher.daemon.server.exec.StartStopIfBuildAndStop.execute(StartStopIfBuildAndStop.java:33)
	at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:71)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:69)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:69)
	at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:34)
	at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:70)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:34)
	at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
	at org.gradle.launcher.daemon.server.exec.DaemonHygieneAction.execute(DaemonHygieneAction.java:39)
	at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:46)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246)
	at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
Caused by: org.gradle.process.internal.ExecException: Process 'command '/usr/lib/jvm/jdk1.8.0/bin/java'' finished with non-zero exit value 1
	at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:365)
	at org.gradle.process.internal.DefaultJavaExecAction.execute(DefaultJavaExecAction.java:31)
	at org.gradle.api.internal.file.DefaultFileOperations.javaexec(DefaultFileOperations.java:145)
	at org.gradle.api.internal.project.AbstractProject.javaexec(AbstractProject.java:784)
	at org.gradle.api.internal.project.AbstractProject.javaexec(AbstractProject.java:780)
	at org.gradle.api.Project$javaexec$15.call(Unknown Source)
	at me.tatarka.RetrolambdaTask.execute(RetrolambdaTask.groovy:69)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:235)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:222)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 54 more

```

**Comment by orfjackal** [comment]
@osayilgan That looks like a different problem. The `java.lang.ClassNotFoundException: android.support.v4.widget.DrawerLayoutImpl` indicates that the Android libraries are not found from the classpath that Retrolambda is configured to use.

**Comment by osayilgan** [comment]
@orfjackal I will try it reproduce it with removing the Retrolambda. Because I've that Android library in the gradle dependencies, it shouldn't be a problem.

**Comment by omjokine** [comment]
I had same problem as @osayilgan: works in local machine but fails in Travis. Problem was 
```java.lang.NoClassDefFoundError: android/support/v4/view/LayoutInflaterFactory```
Managed to fix problem by downgrading support-v4 from 22.1.0 back to 22.0.0

So maybe there's some issue with support-v4:22.1.0

**Comment by osayilgan** [comment]
@omjokine I'm using support v4 22.0.0 and I still have the same issue. CI fails but it's ok in my Local machine. I thought it might have something to do with @aar processing.

**Comment by shekibobo** [comment]
I am seeing this problem after upgrading the android support libs from 22.0 to 22.1.

It will compile fine if I run `./gradlew clean testDebug`, but it will fail if I run the tests like our CI server: `./gradlew clean; ./gradlew assembleDebug; ./gradlew testDebug;`. It seems running `clean` as a separate task is a little more thorough in deleting all build artifacts.

I'm running `gradle-retrolambda:3.0.1`. It still fails if I set `incremental false`.

// @evant 

It looks like retrolambda is able to build a few files until it reaches the first one that subclasses a `support.v4.Fragment`:

```
Saving lambda class: com/myproject/android/controller/supplies/SuppliesFragment$SuppliesListAdapter$$Lambda$1
Saving lambda class: com/myproject/android/view/listitem/OrdinalStringSettingListItemView$$Lambda$1
Saving lambda class: com/myproject/android/view/listitem/OrdinalStringSettingListItemView$$Lambda$2
Saving lambda class: com/myproject/android/data/webservice/listener/GetDefaultLocationSuccessListener$$Lambda$1
Saving lambda class: com/myproject/android/data/webservice/listener/GetDefaultLocationSuccessListener$$Lambda$2
Error! Failed to transform some classes
java.lang.RuntimeException: java.lang.IllegalAccessException: no such method: com.myproject.android.controller.detail.status.AffreshStatusFragment.lambda$setupSupplyView$51(Supply,View)void/invokeSpecial
  at net.orfjackal.retrolambda.lambdas.LambdaReifier.reifyLambdaClass(LambdaReifier.java:42)
  at net.orfjackal.retrolambda.lambdas.BackportLambdaInvocations$InvokeDynamicInsnConverter.backportLambda(BackportLambdaInvocations.java:105)
  at net.orfjackal.retrolambda.lambdas.BackportLambdaInvocations$InvokeDynamicInsnConverter.visitInvokeDynamicInsn(BackportLambdaInvocations.java:94)
  at net.orfjackal.retrolambda.asm.ClassReader.readCode(ClassReader.java:1439)
  at net.orfjackal.retrolambda.asm.ClassReader.readMethod(ClassReader.java:1017)
  at net.orfjackal.retrolambda.asm.ClassReader.accept(ClassReader.java:693)
  at net.orfjackal.retrolambda.asm.ClassReader.accept(ClassReader.java:506)
  at net.orfjackal.retrolambda.Transformers.transform(Transformers.java:96)
  at net.orfjackal.retrolambda.Transformers.backportClass(Transformers.java:44)
  at net.orfjackal.retrolambda.Retrolambda.run(Retrolambda.java:73)
  at net.orfjackal.retrolambda.Main.main(Main.java:26)
Caused by: java.lang.IllegalAccessException: no such method: com.myproject.android.controller.detail.status.AffreshStatusFragment.lambda$setupSupplyView$51(Supply,View)void/invokeSpecial
  at java.lang.invoke.MemberName.makeAccessException(MemberName.java:872)
  at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:993)
  at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1379)
  at java.lang.invoke.MethodHandles$Lookup.findSpecial(MethodHandles.java:997)
  at net.orfjackal.retrolambda.lambdas.Types.toMethodHandle(Types.java:42)
  at net.orfjackal.retrolambda.lambdas.Types.asmToJdkType(Types.java:19)
  at net.orfjackal.retrolambda.lambdas.LambdaReifier.callBootstrapMethod(LambdaReifier.java:106)
  at net.orfjackal.retrolambda.lambdas.LambdaReifier.reifyLambdaClass(LambdaReifier.java:37)
  ... 10 more
Caused by: java.lang.NoClassDefFoundError: android/support/v4/view/LayoutInflaterFactory
  at java.lang.ClassLoader.defineClass1(Native Method)
  at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
  at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
  at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
  at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
  at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
  at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
  at java.security.AccessController.doPrivileged(Native Method)
  at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
  at net.orfjackal.retrolambda.NonDelegatingClassLoader.loadClass(NonDelegatingClassLoader.java:25)
  at java.lang.invoke.MethodHandleNatives.resolve(Native Method)
  at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:965)
  at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:990)
  ... 16 more
Caused by: java.lang.ClassNotFoundException: android.support.v4.view.LayoutInflaterFactory
  at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
  at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
  at java.security.AccessController.doPrivileged(Native Method)
  at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  at net.orfjackal.retrolambda.NonDelegatingClassLoader.loadClass(NonDelegatingClassLoader.java:27)
  ... 29 more
:app:compileRetrolambdaDebug FAILED
:app:compileRetrolambdaDebug (Thread[main,5,main]) completed. Took 0.703 secs.

FAILURE: Build failed with an exception.
```

**Comment by evant** [comment]
@shekibobo It looks like you are running into #105, unlike this issue, it can be consistently reproduced and has something to do with the latests support library. I have a workaround listed there that seems to fix it.

**Comment by Diolor** [comment]
I encountered the error once again.

Here is the source code (inside a method in a Activity):

    public void onAttach(final Activity activity) {
        super.onAttach(activity);
        userStateUpdateAction = (UserModeAndState userModeAndState) -> {
            StateToView stateToView = new StateToView(activity, getFragmentManager());
            stateToView.loadViewForState(userModeAndState.first, userModeAndState.second);
        };
    }

And this is the decompiled source code under the intermediates folder produced with the help of gradle-retrolambda:

    import org.package.android.ui.BaseSupportFragment..Lambda.1;
    ....


    public void onAttach(Activity activity) {
        this.userStateUpdateAction = 1.lambdaFactory$(this, activity);
    }


the correct which should have been produced is:

    import org.package.android.ui.BaseSupportFragment$$Lambda$1;
    ....


    public void onAttach(Activity activity) {
        this.userStateUpdateAction = BaseSupportFragment$$Lambda$1.lambdaFactory$(this, activity);
    }


@orfjackal could you please check?

**Comment by orfjackal** [comment]
@Diolor, the replacement of `$` with `.` is most probably just a bug with the decompiler. `javap` should tell how it really is.

**Comment by NachoSoto** [comment]
We started hitting this issue recently as well. Somehow it's getting more frequent now.
Cleaning and rebuilding temporarily fixes the problem.

I don't think this has anything to do with the support library (at least in our case), as we're reproducing this problem in a pure-java library.

**Comment by ypresto** [comment]
I found `rm -rf app/build` leads to error like `Caused by: java.lang.ClassNotFoundException: android.support.v4.view.LayoutInflaterFactory`.
Then rebuilding succeeds without error, even after clean task has been executed.

**Comment by ypresto** [comment]
```
Executing task ':app:prepareComAndroidSupportSupportV132103Library' (up-to-date check took 0.001 secs) due to:
  Output file /home/ubuntu/Android/app/build/intermediates/exploded-aar/com.android.support/support-v13/21.0.3 has changed.
  Output file /home/ubuntu/Android/app/build/intermediates/exploded-aar/com.android.support/support-v13/21.0.3/jars/libs/internal_impl-21.0.3.jar has been removed.
  Output file /home/ubuntu/Android/app/build/intermediates/exploded-aar/com.android.support/support-v13/21.0.3/AndroidManifest.xml has been removed.
```

Workaround: run prepare***Dependencies task first, then run your build task separatedly.

```
./gradlew prepare${build_variant}Dependencies
./gradlew assemble${build_variant} # you can run clean before assemble
```

**Comment by bjdupuis** [comment]
ypresto's workaround worked for my situation for my CI build. Thanks for that.

**Comment by clemp6r** [comment]
Not sure this is relevant but the coincidence is to strong to ignore it.

I got the same problem (java.lang.NoClassDefFoundError: XXX$$Lambda$) and I noticed it always happen on the same class A after I modified a class B.

A and B are not related, except that **B's name is a suffix of A's name**.
ie.: `a.b.FavoriteItems` and `a.b.Items`

Recently I got the exact same problem with another pair of class, and guess what, the naming is similar, one class name is a suffix of the other class name.

As a workaround I renamed my classes so one is not a suffix of the other.

**Comment by evant** [comment]
@clemp6r Thanks! I think that lead my right to the issue. https://github.com/evant/gradle-retrolambda/blob/master/src/main/groovy/me/tatarka/RetrolambdaTask.groovy#L138 the regex for deleting the related lambda isn't quite right and deletes any lambdas with the same suffix.

**Comment by clemp6r** [comment]
Nice!

**Comment by rspeyer** [comment]
Awesome! This will be a great fix

**Comment by teddis** [comment]
Fantastic! Thank you for discovering that. I hope this fixes it. A long, long running bug indeed!

**Comment by ypresto** [comment]
wow!!! thank you!!! i'll try that fix for incremental build after it is released. :tada: :tada:

**Comment by evant** [comment]
Fixed in `3.2.2`

**Comment by dhenry** [comment]
Brilliant!! Thanks for the fix!

**Comment by IlyaEremin** [comment]
@clemp6r super! Good job

**Comment by teddis** [comment]
Nice sleuthing @clemp6r! This fix needs a virtual celebration.

**Comment by AlmogBaku** [comment]
It's happening to me again with recent version... clean and rebuilding helps, but it happened twice in 10 minutes! :O

**Comment by AlmogBaku** [comment]
Update:
After clean and building it works properly, but then when I try to build it again it crash.

```
12-22 13:40:30.561 31890-32243/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.myproj.android, PID: 31890
                                                   java.lang.NoClassDefFoundError: Failed resolution of: Lcom/myproj/android/fragment/OldMainFragment$$Lambda$1;
                                                       at com.myproj.android.fragment.OldMainFragment.<init>(OldMainFragment.java:198)
                                                       at com.myproj.android.fragment.OldMainFragment_.<init>(OldMainFragment_.java:23)
                                                       at com.myproj.android.fragment.MainFragment.onViewCreated(MainFragment.java:28)
                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1086)
                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
                                                       at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
                                                       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1613)
                                                       at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:330)
                                                       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:547)
                                                       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1259)
                                                       at android.app.Activity.performStart(Activity.java:6026)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2302)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2413)
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:155)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:135)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5343)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.myproj.android.fragment.OldMainFragment$$Lambda$1" on path: DexPathList[[zip file "/data/app/com.myproj.android-2/base.apk"],nativeLibraryDirectories=[/data/app/com.myproj.android-2/lib/arm, /vendor/lib, /system/lib]]
                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                       at com.myproj.android.fragment.OldMainFragment.<init>(OldMainFragment.java:198) 
                                                       at com.myproj.android.fragment.OldMainFragment_.<init>(OldMainFragment_.java:23) 
                                                       at com.myproj.android.fragment.MainFragment.onViewCreated(MainFragment.java:28) 
                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1086) 
                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248) 
                                                       at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738) 
                                                       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1613) 
                                                       at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:330) 
                                                       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:547) 
                                                       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1259) 
                                                       at android.app.Activity.performStart(Activity.java:6026) 
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2302) 
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2413) 
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:155) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:135) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5343) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:372) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700) 
                                                   	Suppressed: java.lang.ClassNotFoundException: com.myproj.android.fragment.OldMainFragment$$Lambda$1
                                                       at java.lang.Class.classForName(Native Method)
                                                       at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                       at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                       		... 23 more
                                                    Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
```

**Comment by AlmogBaku** [comment]
My bad, I had to upgrade the gradle plugin :O

Thanks for the solution!

**Comment by monemihir** [comment]
i've just encountered this exact same issue.

i'm using **retrolambda 3.6.0**, **gradle 2.3.0**, compiled with **SDK25**, running on device with **SDK17**

seems like the issue has crept back even though it was fixed in ```3.2.2```

**Comment by optisamit** [comment]
I have the same issue as @monemihir, but device is *SDK 19*

**Comment by evant** [comment]
@monemihir can you open a new issue on gradle-retrolambda? I wonder if it's related to https://github.com/evant/gradle-retrolambda/commit/301d176050001d442d2e596af293513b2c3917c9

**Comment by icaromagalhaes** [comment]
Same here! same as @monemihir

**Comment by icaromagalhaes** [comment]
Same here! @monemihir
Also using retrolambda 3.6.0, gradle 2.3.0, compiled with SDK25.

**Comment by pcdroidski** [comment]
Having the same problem. Running an app on an Android device running Marshmallow & below causes NoClassDefFoundError crashes all over. 
Retrolambda 3.6.0, Gradle 2.3.0, Android API 25.

**Comment by luisalduucin** [comment]
If you are using multiDex ... I solved in this way:

In your manifest ... If you do not override the Application class then:
`<application
            android:name="android.support.multidex.MultiDexApplication" >`

If you override it, make sure that you are not extending from Application, instead you should extend from MultiDexApplication and in your manifest should be something like this :
`<application
            android:name="yourOverridingClass" >`
